artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/7e9a831e54da473a9e60c17af9921cd2/artifacts
end_time: 1764527054152
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7e9a831e54da473a9e60c17af9921cd2
run_name: amazing-stoat-707
source_name: ''
source_type: 4
source_version: ''
start_time: 1764527054127
status: 3
tags: []
user_id: adarshkumar
