artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/d6d0a791a7bd4dc78b39e9b34ff43049/artifacts
end_time: 1764527055910
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d6d0a791a7bd4dc78b39e9b34ff43049
run_name: kindly-squirrel-680
source_name: ''
source_type: 4
source_version: ''
start_time: 1764527055898
status: 3
tags: []
user_id: adarshkumar
