artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/e3d40486742c4e088444d3331684be13/artifacts
end_time: 1764526933559
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e3d40486742c4e088444d3331684be13
run_name: clumsy-crab-536
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526933545
status: 3
tags: []
user_id: adarshkumar
