artifact_location: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0
creation_time: 1764526624021
experiment_id: '0'
last_update_time: 1764526624021
lifecycle_stage: active
name: Default
