artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/2b1557f7a24340648062d1d499d6cbd0/artifacts
end_time: 1764526799789
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2b1557f7a24340648062d1d499d6cbd0
run_name: righteous-fly-357
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526799772
status: 3
tags: []
user_id: adarshkumar
