artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/5b1bbe82b27f4d28b4adaada5bcc81e4/artifacts
end_time: 1764527007708
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5b1bbe82b27f4d28b4adaada5bcc81e4
run_name: bemused-fox-544
source_name: ''
source_type: 4
source_version: ''
start_time: 1764527007696
status: 3
tags: []
user_id: adarshkumar
