artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/0b38a4d79df04bb0ba23354a0526ca8e/artifacts
end_time: 1764526971820
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0b38a4d79df04bb0ba23354a0526ca8e
run_name: calm-sponge-281
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526971807
status: 3
tags: []
user_id: adarshkumar
