artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/bf40d3c33ecf461f857446222d4dc2dc/artifacts
end_time: 1764526749454
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bf40d3c33ecf461f857446222d4dc2dc
run_name: stately-mule-910
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526749433
status: 3
tags: []
user_id: adarshkumar
