artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/9c5328199a184ecb9df131f6eb7d1ec1/artifacts
end_time: 1764526915749
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9c5328199a184ecb9df131f6eb7d1ec1
run_name: legendary-donkey-633
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526915697
status: 3
tags: []
user_id: adarshkumar
