artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/6038edf0609a4efaa707c054bce34515/artifacts
end_time: 1764526624095
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6038edf0609a4efaa707c054bce34515
run_name: nimble-ape-969
source_name: ''
source_type: 4
source_version: ''
start_time: 1764526624085
status: 3
tags: []
user_id: adarshkumar
