artifact_uri: /Users/adarshkumar/Developer/mlops/MLflow/Check LocalHost Connection/0/79bfdba3fd4344b79dfc6483c2ed51aa/artifacts
end_time: 1764527146029
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 79bfdba3fd4344b79dfc6483c2ed51aa
run_name: crawling-horse-858
source_name: ''
source_type: 4
source_version: ''
start_time: 1764527146018
status: 3
tags: []
user_id: adarshkumar
